using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using NUnit.Framework;

namespace Class1
{
    [TestFixture]
    public class Bar
    {
        [Test]
        public void Download(int a)
        {
            Assert.Fail("autogenerated");
        }
        [Test]
        public void Go(List<int> a)
        {
            Assert.Fail("autogenerated");
        }
    }
}
