using System;
using System.Collections.Generic;
using System.Text;
using NUnit.Framework;

namespace TestClasses
{
    [TestFixture]
    public class Class2
    {
        [Test]
        public void SendMess(string mess)
        {
            Assert.Fail("autogenerated");
        }
    }
}
